package com.web.orm;

/**
 * TLiuyan generated by MyEclipse Persistence Tools
 */

public class TLiuyan implements java.io.Serializable
{
	private Integer id;//留言ID
	private String neirong;//留言内容
	private String liuyanshi;//留言时间
	private String user_id;//用户ID

	private String huifu;//回复内容
	private String huifushi;//回复时间
	
	private Tuser user;

	public String getHuifu()//得到回复内容
	{
		return huifu;
	}

	public void setHuifu(String huifu)//设置回复内容
	{
		this.huifu = huifu;
	}

	public String getHuifushi()//得到回复时间
	{
		return huifushi;
	}

	public void setHuifushi(String huifushi)//设置回复时间
	{
		this.huifushi = huifushi;
	}

	public Integer getId()//得到回复ID
	{
		return id;
	}

	public void setId(Integer id)//设置回复ID
	{
		this.id = id;
	}

	public String getLiuyanshi()//得到回复时间
	{
		return liuyanshi;
	}

	public void setLiuyanshi(String liuyanshi)//设置回复时间
	{
		this.liuyanshi = liuyanshi;
	}

	public String getNeirong()//得到回复内容
	{
		return neirong;
	}

	public void setNeirong(String neirong)//设置回复内容
	{
		this.neirong = neirong;
	}

	public Tuser getUser()//得到留言用户
	{
		return user;
	}

	public void setUser(Tuser user)//设置留言用户
	{
		this.user = user;
	}

	public String getUser_id()//得到留言用户ID
	{
		return user_id;
	}

	public void setUser_id(String user_id)//设置留言用户ID
	{
		this.user_id = user_id;
	}

	
}